---
- hosts: all
  gather_facts: yes
  become: true

  vars:
    root_passwd: "{{ lookup('env','PASSWD') }}"
    sudo_user:   "{{ lookup('env','USER') }}"
    hostname:    "{{ lookup('env','HOSTNAME') }}"
    timezone:    "{{ lookup('env','TIMEZONE') | default('America/Sao_Paulo') }}"
    packages:
      - bash-completion
      - epel-release
      - sudo
      - curl
      - nano
      - git
      - chrony

  tasks:
    - fail:
        msg: "Este playbook roda exclusivamente em sistemas RockyLinux/CentOS!"
      when:
        - ansible_distribution != 'Rocky'
        - ansible_distribution != 'CentOS'

    - name: Change password for root user
      user:
        name: root
        state: present
        password: "{{ root_passwd | password_hash('sha512') }}"
      when: 
        - root_passwd is defined
        - root_passwd != ""

    - name: Enable password SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: Change authorized_keys file
      script: ../scripts/root.sh
      args:
        executable: /bin/bash

    - name: "Set hostname to {{ hostname }}"
      hostname:
        name: "{{ hostname }}"
        use: systemd
      when: 
        - hostname is defined
        - hostname != ""

    - name: "Set pretty hostname to {{ hostname }}"
      shell: "hostnamectl set-hostname {{ hostname }} --pretty"
      when: 
        - hostname is defined
        - hostname != ""

    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Install required system packages
      dnf:
        name: "{{ packages }}"
        state: latest
      when: 
        - packages is defined
        - packages != ""

    - name: "Set timezone to {{ timezone }}"
      timezone:
        name: "{{ timezone }}"
        hwclock: yes
      when: 
        - timezone is defined
        - timezone != ""

    - name: Make sure chronyd is started, and is enabled on restart.
      service:
        name: chronyd
        state: started
        enabled: yes
      when: 
        - timezone is defined
        - timezone != ""

    - name: Restart crond
      service:
        name: crond
        state: restarted
      when: 
        - timezone is defined
        - timezone != ""

    - name: Setup passwordless wheel
      lineinfile:
        path: /etc/sudoers
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
        state: present
      when: 
        - sudo_user is defined
        - sudo_user != ""

    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ sudo_user }}"
        state: present
        groups: wheel
        append: true
        create_home: true
      when: 
        - sudo_user is defined
        - sudo_user != ""

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ sudo_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      when: 
        - sudo_user is defined
        - sudo_user != ""
        - lookup('env','VAGRANT') is not defined

    - name: Restart sshd
      service:
        name: sshd
        state: restarted

    - name: Download ix
      get_url:
        url: http://ix.io/client
        dest: /usr/local/bin/ix
        mode: '0755'