---
- hosts: all
  become: true

  vars:
    domain:    "{{ lookup('env','SITE') }}"
    cf_email:  "{{ lookup('env','CF_EMAIL') }}"
    cf_token:  "{{ lookup('env','CF_TOKEN') }}"
  
  tasks:
    - fail:
        msg: "Use SITE env variable with your site domain"
      when: 
        - (domain is not defined or domain == "")
        - (cf_email is not defined or cf_email == "")
        - (cf_token is not defined or cf_token == "")

    - name: Install required system packages
      dnf:
        name:
          - epel-release
          - certbot
          - python3-certbot-dns-cloudflare
        state: latest

    - name: "Create /etc/cloudflare.ini"
      template:
        src: "../templates/cloudflare/cloudflare.ini.j2"
        dest: "/etc/cloudflare.ini"
        mode: '0600'
        force: yes

    - name: Check if the cert exists
      stat:
        path: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
      register: cert_file_result

    - name: "Run certbot command for {{ domain }}"
      command: certbot certonly --agree-tos --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare.ini -d "{{ domain }}" -d "*.{{ domain }}"
      when: 
        - not cert_file_result.stat.exists