Vagrant.configure("2") do |config|
    config.vm.box = "rockylinux/8"
    config.vm.network "forwarded_port", id: "ssh", host: 2024, guest: 22
    config.vm.network "forwarded_port", guest: 8000, host: 8000
    config.vm.synced_folder "../templates", "/vagrant/templates/"

    config.vm.provider :virtualbox do |vb|
        vb.name = "rocky"
        config.vm.box_version = "4.0.0"
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yml"
    end
end
