---
- hosts: all
  become: true
  
  tasks:
    - fail:
        msg: "Este playbook roda exclusivamente em sistemas Ubuntu!"
      when: ansible_distribution != 'Ubuntu'

    - name: Update apt repo and cache
      apt: 
        cache_valid_time: 3600
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install update-manager-core
      apt:
        pkg: update-manager-core
        state: latest

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Check if a reboot is needed
      register: reboot_required
      stat:
        path: /var/run/reboot-required
        get_md5: no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required.stat.exists

    - name: Ensure Prompt is set to normal in /etc/update-manager/release-upgrades
      lineinfile:
        path: /etc/update-manager/release-upgrades
        regexp: '^Prompt='
        line: Prompt=normal
        backrefs: yes
      check_mode: yes
      register: conf
  
    # command: do-release-upgrade -d -f DistUpgradeViewNonInteractive
    - name: Upgrading Ubuntu to next release
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      when: conf is changed

    - name: Reboot if have a release upgrade
      reboot:
        msg: "Reboot initiated by Ansible for release upgrade"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: conf is changed
