Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
	config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.network "forwarded_port", id: "ssh", host: 2023, guest: 22
    config.vm.network "forwarded_port", id: "icecast2", host: 8000, guest: 8000
    config.vm.synced_folder "../templates", "/vagrant/templates/"
    
    config.vm.provider :virtualbox do |vb|
        vb.name = "ubuntu"
    end
end
