Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    config.vm.network "forwarded_port", id: "ssh", host: 2022, guest: 22
    config.vm.network "forwarded_port", guest: 8000, host: 8000
    config.vm.synced_folder "../templates", "/vagrant/templates/"
    
    config.vm.provider :virtualbox do |vb|
        vb.name = "debian"
    end
end