---
- hosts: all
  become: true
  gather_facts: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: OS Family
      debug: msg="{{ ansible_os_family }}"
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"