---
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Download file
      get_url:
        url: "https://site.com/file.tar.gz"
        dest: "/tmp/file.tar.gz"
        owner: user
        group: group
        mode: '0644'