---
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure group group exists
      ansible.builtin.group:
        name: group_name
        state: present

    - name: Create a 2048-bit SSH key for user user in ~/nginx/.ssh/id_rsa
      ansible.builtin.user:
        name: user_name
        shell: /bin/bash
        home: /home/user_name
        password: "{{ user_name_password | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        state: present